In [1]:
import numpy as np
import pandas as pd
from make_cache import main, decryption
num_threads = 8
max_n_plus = 5
seed = np.random.randint(10000)
# seed = 2062
# seed = 1986
# seed = 9852
for n_plus in range(1, max_n_plus + 1):
    main(n_plus,num_threads,len_x=40, log_interval=3, seed=seed)

2025-04-09 15:45:46,577 : numba=0.61.0, numpy=2.1.3
2025-04-09 15:45:46,577 : OPT=_OptLevel(3), THREADING_LAYER=default
2025-04-09 15:45:46,577 : USING_SVML=False, ENABLE_AVX=True, DISABLE_JIT=0
2025-04-09 15:45:46,578 : max_op = 1  ,  date : 2025-04-09 15:45:46.578038
2025-04-09 15:45:46,578 : use cores : 8
2025-04-09 15:45:46,578 : making random_x
2025-04-09 15:45:46,578 :    seed = 2750, loop = 100000, upper = 0.5, lower = 1.5
2025-04-09 15:45:47,045 : random_x corrcoef = 1.9687900115668946e-06
2025-04-09 15:45:47,419 : make_before_similar_num_list
2025-04-09 15:45:47,420 :    using Memory size =  194.4 MB
2025-04-09 15:45:47,420 :    Memory size of numpy array = 0.0 M bytes +alpha (1data=1280 bytes, loop=2)
2025-04-09 15:45:50,552 :       0/2  (225.2 MB)  0:00:03.005017 : inf
2025-04-09 15:45:53,566 :       0/2  (248.8 MB)  0:00:06.017818 : inf
2025-04-09 15:45:54,475 :    time : 0:00:07.054403
2025-04-09 15:45:54,475 : make_unique_equations
2025-04-09 15:45:54,475 :    n_op1 = 0, 

In [2]:
import numpy as np
np.linspace(0, 0 - 1, 0 + 1).astype("int64")

array([0])

In [ ]:
46.621827

In [4]:
loop = 100
n_split  = 10
np.linspace(0, loop-1, n_split + 1).astype("int64")

array([ 0,  9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [ ]:
[2, 10, 80, 911, 13471, 251705, 5561536]
630:281
10208:3263
201552:50153

SyntaxError: illegal target for annotation (3326823552.py, line 2)

1 : 201838:49888   
4 : 201838:49888   
8 : 201838:49888   

2, 10, 80, 911, 13471, 251726   
1 : 6:4   
2 : 53:27   
3 : 636:275   
4 : 10241:3230   
5 : 201838:49888   

In [ ]:
#np.save("arr_len", np.array([2],dtype="int64"))
#np.save("operator_0",np.array([[1],[0]],dtype="int8"))
#np.savez(f"check_change_x_tot_0", np.full((2, 2, 2), -100, dtype="int8"))

In [ ]:
np.load("operator_0.npy")

In [ ]:
np.arange(2,dtype="int8")[::-1].reshape((-1,1))

In [ ]:
np.load("check_change_x_tot_0.npz")["arr_0"]

In [ ]:
import numpy as np
from numba import njit, prange
from numba_progress.numba_atomic import atomic_add, atomic_xchg,atomic_min

@njit()
def fibo(n):
    a, b = 0, 1
    fibolist=np.zeros(n)
    for i in range(n):
        a, b = b, a+b
        fibolist[i]=a


@njit(parallel=True, error_model="numpy")
def func(loop, target_num, num_threads = 8):
    weight = 100
    counter = np.zeros(num_threads, dtype="int64")
    checked = np.zeros(1, dtype="int8")
    for thread_id in prange(num_threads):
        for i in range(thread_id, loop, num_threads):
            if checked[0] == 1:
                break
            for j in range(weight):
                fibo(10000)
            counter[thread_id] = i
            if target_num == i:
                atomic_add(checked,0,1)
                break
    return counter
loop = 100000
target_num = 30
func(loop, target_num)

In [ ]:
import numpy as np
from numba import njit, prange
from numba_progress.numba_atomic import atomic_add, atomic_xchg,atomic_min

@njit()
def fibo(n):
    a, b = 0, 1
    fibolist=np.zeros(n)
    for i in range(n):
        a, b = b, a+b
        fibolist[i]=a


@njit(parallel=True, error_model="numpy")
def func(loop, target_num, num_threads = 8):
    weight = 100
    counter = np.zeros(num_threads, dtype="int64")
    checked = np.zeros(1, dtype="int8")
    for i in prange(loop):
        if checked[0] == 0:
            for j in range(weight):
                fibo(10000)
            counter[i % num_threads] = i
            if target_num == i:
                atomic_add(checked,0,1)
    return counter, checked
loop = 100000
target_num = 30
func(loop, target_num)

In [ ]:
np.random.seed(100)
max_op = 5
len_x = 300

#logger.info("making random_x")
save_random_x = np.random.uniform(0.3, 10, (max_op + 2, len_x))
save_corrcoef = np.max(np.abs(np.corrcoef(save_random_x[1:]) - np.eye(max_op + 1)))
for i in range(100000):
    random_x = np.random.uniform(0.3, 10, (max_op + 2, len_x))
    corrcoef = np.max(np.abs(np.corrcoef(random_x[1:]) - np.eye(max_op + 1)))
    if save_corrcoef > corrcoef:
        save_corrcoef = corrcoef
        save_random_x = random_x
random_x = save_random_x.copy()
random_x[0] = 1

In [ ]:
from numba import njit
@njit
def func(max_op, len_x):
    save_random_x = np.random.uniform(0.3, 10, (max_op + 2, len_x))
    save_corrcoef = np.max(np.abs(np.corrcoef(save_random_x[1:]) - np.eye(max_op + 1)))
    for _ in range(100000):
        random_x = np.random.uniform(0.3, 10, (max_op + 2, len_x))
        corrcoef = np.max(np.abs(np.corrcoef(random_x[1:]) - np.eye(max_op + 1)))
        if save_corrcoef > corrcoef:
            save_corrcoef = corrcoef
            save_random_x = random_x
    random_x = save_random_x.copy()
    random_x[0] = 1
    print(save_corrcoef)
max_op = 5
len_x = 300
func(max_op, len_x)

In [ ]:
func(max_op, len_x)

In [ ]:
np.random.uniform(-10, 10)

In [ ]:
from numba import njit
import numpy as np

@njit
def corrcoef(x_1, x_2):
    mean_1, mean_2 = np.mean(x_1), np.mean(x_2)
    x_len = x_1.shape[0]
    sum_1, sum_2, cov = 0.0, 0.0, 0.0
    for i in range(x_len):
        sum_1 += (x_1[i] - mean_1)**2
        sum_2 += (x_2[i] - mean_2)**2
        cov += (x_1[i] - mean_1) * (x_2[i] - mean_2)
    return np.abs(cov / np.sqrt(sum_1 * sum_2))

@njit
def func(max_op, len_x, seed=-100, loop=100000, upper=0.3, lower=10):
    if seed != -100:
        np.random.seed(seed)
    save_random_x = np.random.uniform(upper,lower , (max_op + 2, len_x))
    save_corrcoef = 0
    for i in range(1, max_op + 1):
        for j in range(i + 1, max_op + 2):
            new_corrcoef = corrcoef(save_random_x[i], save_random_x[j])
            if new_corrcoef > save_corrcoef:
                save_corrcoef = new_corrcoef
    for _ in range(loop):
        random_x = np.random.uniform(upper, lower, (max_op + 2, len_x))
        now_corrcoef = 0
        for i in range(1, max_op + 1):
            for j in range(i + 1, max_op + 2):
                new_corrcoef = corrcoef(random_x[i], random_x[j])
                if new_corrcoef > now_corrcoef:
                    now_corrcoef = new_corrcoef
        if save_corrcoef > now_corrcoef:
            save_corrcoef = now_corrcoef
            save_random_x = random_x
    save_random_x[0] = 1
    return save_corrcoef, save_random_x

In [ ]:
max_op = 5
len_x = 300
func(max_op, len_x,seed=-100, loop=1000000, upper=-10, lower=10)[0]

In [ ]:
len_random_x = 50
max_op = 7
mem_size_per_1data = (  # Byte
    len_random_x * 8  # save_similar_num_list
    + 1 * 8  # head_save_similar_num_list
    + 1  # TF_list
    + 1  # check_exist_TF
    + (2 * max_op + 1)  # save_equation_list
    + 5 * 8  # save_base_eq_id_list
    + max_op  # save_back_change_pattern
    + (max_op * (max_op + 1))  # save_check_change_x_tot
    + (max_op * (max_op + 1))  # save_check_change_x_ones
)
mem_size_per_1data*129316244//1000000000

75

In [ ]:
import platform
import resource

def get_maxrss() -> float:
    system = platform.system()
    r = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
    if system == "Darwin":
        return r / 1024 / 1024  # bytes on MacOS
    return r / 1024  # kilobytes on Linux
get_maxrss()

62.484375

In [ ]:
import numpy as np
from sys import getsizeof
import resource
start_using_mem = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
print(start_using_mem)
a = np.random.random((1000,10000))
print(getsizeof(a), start_using_mem + getsizeof(a))
print(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)

156876800
80000128 236876928
236863488


In [ ]:
import resource
def str_using_mem():
    using_mem = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
    return f"{using_mem /(1024**2):.1f} MB"
str_using_mem()

'225.9 MB'

In [ ]:
import numpy as np
a = np.random.random((1000,10000))
a.__sizeof__()

80000128

In [ ]:
import numpy as np
from numba import njit
@njit(error_model="numpy")
def numba_del():
    a = np.random.random((1000,10000))
    del a
a = np.random.random((1000,10000))
print(a.__sizeof__())
numba_del()
# print(a.__sizeof__())

80000128


CompilerError: Failed in nopython mode pipeline (step: analyzing bytecode)
Illegal IR, del found at: del a

File "../../../../../../../../var/folders/tj/kgkr2hgj2csbcqdhnxjz2_nh0000gn/T/com.apple.shortcuts.mac-helper/ipykernel_16659/3546667526.py", line 6:
<source missing, REPL/exec in use?>


In [2]:
import numpy as np
np.sqrt(5434016)

np.float64(2331.0975955545064)

In [13]:
n_split = 100
len_= 100033
np.linspace(0, len_-1, n_split + 1).astype("int64")

array([     0,   1000,   2000,   3000,   4001,   5001,   6001,   7002,
         8002,   9002,  10003,  11003,  12003,  13004,  14004,  15004,
        16005,  17005,  18005,  19006,  20006,  21006,  22007,  23007,
        24007,  25008,  26008,  27008,  28008,  29009,  30009,  31009,
        32010,  33010,  34010,  35011,  36011,  37011,  38012,  39012,
        40012,  41013,  42013,  43013,  44014,  45014,  46014,  47015,
        48015,  49015,  50016,  51016,  52016,  53016,  54017,  55017,
        56017,  57018,  58018,  59018,  60019,  61019,  62019,  63020,
        64020,  65020,  66021,  67021,  68021,  69022,  70022,  71022,
        72023,  73023,  74023,  75024,  76024,  77024,  78024,  79025,
        80025,  81025,  82026,  83026,  84026,  85027,  86027,  87027,
        88028,  89028,  90028,  91029,  92029,  93029,  94030,  95030,
        96030,  97031,  98031,  99031, 100032])