In [1]:
import numpy as np
import pandas as pd
from make_cache import main, decryption

In [2]:
num_threads = 8
max_n_plus = 4
for n_plus in range(1, max_n_plus + 1):
    main(n_plus,num_threads,len_x=40, log_interval=30)

2025-03-13 11:09:03,026 : numba=0.60.0, numpy=2.0.2
2025-03-13 11:09:03,026 : OPT=_OptLevel(3), THREADING_LAYER=default
2025-03-13 11:09:03,027 : USING_SVML=False, ENABLE_AVX=True, DISABLE_JIT=0
2025-03-13 11:09:03,027 : max_op = 1  ,  date : 2025-03-13 11:09:03.027285
2025-03-13 11:09:03,027 : use cores : 8
2025-03-13 11:09:03,027 : making random_x
2025-03-13 11:09:03,563 : random_x corrcoef = 1.7551310817054759e-06
2025-03-13 11:09:03,981 : make_before_similar_num_list
2025-03-13 11:09:03,981 :    Memory size of numpy array = 0.0 M bytes +alpha (1data=1280 bytes, loop=2)
2025-03-13 11:09:08,293 :    time : 0:00:04.311695
2025-03-13 11:09:08,294 : make_unique_equations
2025-03-13 11:09:08,294 :    n_op1 = 0, n_op2 = 0
2025-03-13 11:09:09,934 :       make_unique_equations_thread
2025-03-13 11:09:09,934 :          Memory size of numpy array = 0.0 M bytes +alpha (1data=698 bytes, size_arr_for_mem=20)
2025-03-13 11:09:25,735 :          time : 0:00:15.800888
2025-03-13 11:09:25,736 :      

[ 1  2  1 -4  2 -3  1 -2 -4]
[[0 1 2]
 [0 2 1]] [0 1] [0 0] [ True  True]
True True [] [[1 2]]


In [ ]:
[2, 10, 80, 911, 13471, 251730, 5561536]

1 : 201838:49888   
4 : 201838:49888   
8 : 201838:49888   

In [ ]:
need calc  201844:49884

2, 10, 80, 911, 13471, 251726   
1 : 6:4   
2 : 53:27   
3 : 636:275   
4 : 10241:3230   
5 : 201838:49888   

In [ ]:
#np.save("arr_len", np.array([2],dtype="int64"))
#np.save("operator_0",np.array([[1],[0]],dtype="int8"))
#np.savez(f"check_change_x_tot_0", np.full((2, 2, 2), -100, dtype="int8"))

In [ ]:
np.load("operator_0.npy")

In [ ]:
np.arange(2,dtype="int8")[::-1].reshape((-1,1))

In [ ]:
np.load("check_change_x_tot_0.npz")["arr_0"]

In [ ]:
import numpy as np
from numba import njit, prange
from numba_progress.numba_atomic import atomic_add, atomic_xchg,atomic_min

@njit()
def fibo(n):
    a, b = 0, 1
    fibolist=np.zeros(n)
    for i in range(n):
        a, b = b, a+b
        fibolist[i]=a


@njit(parallel=True, error_model="numpy")
def func(loop, target_num, num_threads = 8):
    weight = 100
    counter = np.zeros(num_threads, dtype="int64")
    checked = np.zeros(1, dtype="int8")
    for thread_id in prange(num_threads):
        for i in range(thread_id, loop, num_threads):
            if checked[0] == 1:
                break
            for j in range(weight):
                fibo(10000)
            counter[thread_id] = i
            if target_num == i:
                atomic_add(checked,0,1)
                break
    return counter
loop = 100000
target_num = 30
func(loop, target_num)

In [ ]:
import numpy as np
from numba import njit, prange
from numba_progress.numba_atomic import atomic_add, atomic_xchg,atomic_min

@njit()
def fibo(n):
    a, b = 0, 1
    fibolist=np.zeros(n)
    for i in range(n):
        a, b = b, a+b
        fibolist[i]=a


@njit(parallel=True, error_model="numpy")
def func(loop, target_num, num_threads = 8):
    weight = 100
    counter = np.zeros(num_threads, dtype="int64")
    checked = np.zeros(1, dtype="int8")
    for i in prange(loop):
        if checked[0] == 0:
            for j in range(weight):
                fibo(10000)
            counter[i % num_threads] = i
            if target_num == i:
                atomic_add(checked,0,1)
    return counter, checked
loop = 100000
target_num = 30
func(loop, target_num)

In [ ]:
np.random.seed(100)
max_op = 5
len_x = 300

#logger.info("making random_x")
save_random_x = np.random.uniform(0.3, 10, (max_op + 2, len_x))
save_corrcoef = np.max(np.abs(np.corrcoef(save_random_x[1:]) - np.eye(max_op + 1)))
for i in range(100000):
    random_x = np.random.uniform(0.3, 10, (max_op + 2, len_x))
    corrcoef = np.max(np.abs(np.corrcoef(random_x[1:]) - np.eye(max_op + 1)))
    if save_corrcoef > corrcoef:
        save_corrcoef = corrcoef
        save_random_x = random_x
random_x = save_random_x.copy()
random_x[0] = 1

In [ ]:
from numba import njit
@njit
def func(max_op, len_x):
    save_random_x = np.random.uniform(0.3, 10, (max_op + 2, len_x))
    save_corrcoef = np.max(np.abs(np.corrcoef(save_random_x[1:]) - np.eye(max_op + 1)))
    for _ in range(100000):
        random_x = np.random.uniform(0.3, 10, (max_op + 2, len_x))
        corrcoef = np.max(np.abs(np.corrcoef(random_x[1:]) - np.eye(max_op + 1)))
        if save_corrcoef > corrcoef:
            save_corrcoef = corrcoef
            save_random_x = random_x
    random_x = save_random_x.copy()
    random_x[0] = 1
    print(save_corrcoef)
max_op = 5
len_x = 300
func(max_op, len_x)

In [ ]:
func(max_op, len_x)

In [ ]:
np.random.uniform(-10, 10)

In [ ]:
from numba import njit
import numpy as np

@njit
def corrcoef(x_1, x_2):
    mean_1, mean_2 = np.mean(x_1), np.mean(x_2)
    x_len = x_1.shape[0]
    sum_1, sum_2, cov = 0.0, 0.0, 0.0
    for i in range(x_len):
        sum_1 += (x_1[i] - mean_1)**2
        sum_2 += (x_2[i] - mean_2)**2
        cov += (x_1[i] - mean_1) * (x_2[i] - mean_2)
    return np.abs(cov / np.sqrt(sum_1 * sum_2))

@njit
def func(max_op, len_x, seed=-100, loop=100000, upper=0.3, lower=10):
    if seed != -100:
        np.random.seed(seed)
    save_random_x = np.random.uniform(upper,lower , (max_op + 2, len_x))
    save_corrcoef = 0
    for i in range(1, max_op + 1):
        for j in range(i + 1, max_op + 2):
            new_corrcoef = corrcoef(save_random_x[i], save_random_x[j])
            if new_corrcoef > save_corrcoef:
                save_corrcoef = new_corrcoef
    for _ in range(loop):
        random_x = np.random.uniform(upper, lower, (max_op + 2, len_x))
        now_corrcoef = 0
        for i in range(1, max_op + 1):
            for j in range(i + 1, max_op + 2):
                new_corrcoef = corrcoef(random_x[i], random_x[j])
                if new_corrcoef > now_corrcoef:
                    now_corrcoef = new_corrcoef
        if save_corrcoef > now_corrcoef:
            save_corrcoef = now_corrcoef
            save_random_x = random_x
    save_random_x[0] = 1
    return save_corrcoef, save_random_x

In [ ]:
max_op = 5
len_x = 300
func(max_op, len_x,seed=-100, loop=1000000, upper=-10, lower=10)[0]