In [10]:
from util_for_test import make_unique_eqs, random_test, finder
import numpy as np
max_n_op = 4
find = ["not_calced", "many_calc"]# ["not_calced"]#
upper = 1.5
lower = 0.5
len_x = 300
x = np.random.uniform(lower, upper, (max_n_op + 1, len_x))
calced_x, calced_eq, arr_columns = make_unique_eqs(x, max_n_op)

In [11]:
target_eq = np.array([1,2,3,-4,4,-3,1,-2,-4])
finder(target_eq)

doing : make calced_x
done : make calced_x
finding : 
same :  [ 1  2  4 -3  3 -4  1 -2 -4]
done : make random_x


In [12]:
n_random = 100000
random_test(max_n_op,n_random,x=x,calced_x=calced_x,calced_eq=calced_eq,find=["not_calced", "many_calc"])

doing : make random_x
done : make random_x
all calced.


In [9]:
from util_for_test import finder
import numpy as np
target_eq = np.array([1, 1, -3, 2, -4, 2, -2])
finder(target_eq)

doing : make calced_x
done : make calced_x
finding : 
same :  [ 1  2 -4  1 -3  2 -2]
done : make random_x


In [ ]:
[ 1  2  2 -3  1 -4  1 -2 -4]

In [ ]:
not calced :  [ 2  2  4  1  5 -4 -3 -2 -4] 0.09279815643807351
not calced :  [ 5  5  3  4  2 -4 -3 -1 -4] 1.622520828752577
not calced :  [ 4  5  1 -3  2 -4  4 -2 -4] 0.05453123325323784
not calced :  [ 5  5  1  4  2 -4 -3 -2 -4] 0.157141080172706
not calced :  [ 5  5  4  2  1 -4 -3 -2 -4] 0.05453123325323879
not calced :  [ 5  5  1  5 -4  1 -3 -1 -4] 1.5912550351971864
not calced :  [ 3  2  1 -4  5 -3  3 -2 -4] 0.1057777231470847
not calced :  [ 3  4  4 -3  3 -4  3 -2 -4] 0.0704404922652119
not calced :  [ 4  4  3  1 -4  2 -3 -1 -4] 0.8468567934189181

In [82]:
from numba import njit, prange
import numpy as np

@njit(parallel=True, error_model="numpy")
def check_multi_or(arr_len, num_threads=8):
    save = np.zeros(arr_len, dtype="bool")
    a = np.zeros((num_threads, arr_len), dtype="bool")
    for thread_id in prange(num_threads):
        indexes = np.random.permutation(np.arange(arr_len))[:arr_len//num_threads]
        for i in indexes:
            a[thread_id, i] = True
            save[i] = True
    b = np.zeros(arr_len, dtype="bool")
    for thread_id in range(num_threads):
        b|=a[thread_id]
    return np.all(save == b)
check_multi_or(1000000, num_threads=18)

True

In [74]:
from numba import njit, prange
import numpy as np

@njit(parallel=True, error_model="numpy")
def check_multi_plus(arr_len, num_threads=8):
    save = np.zeros(arr_len, dtype="int64")
    a = np.zeros((num_threads, arr_len), dtype="int64")
    for thread_id in prange(num_threads):
        indexes = np.random.permutation(np.arange(arr_len))[:arr_len//num_threads + 1]
        for i in indexes:
            a[thread_id, i] += 1
            save[i] += 1
    b = np.zeros(arr_len, dtype="int64")
    for thread_id in range(num_threads):
        b+=a[thread_id]
    #return np.all(save == b)
    return save, b, np.all(save == b)
check_multi_plus(100, num_threads=18)

(array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 2, 0, 1, 1, 2, 0, 3, 0, 1, 2,
        0, 2, 1, 1, 1, 0, 0, 2, 3, 2, 0, 3, 0, 3, 1, 0, 2, 1, 2, 0, 0, 0,
        1, 4, 1, 0, 2, 1, 1, 2, 1, 1, 0, 3, 0, 2, 2, 1, 0, 2, 0, 0, 3, 1,
        2, 4, 1, 1, 1, 1, 3, 0, 0, 1, 2, 1, 0, 1, 3, 0, 2, 1, 0, 2, 2, 1,
        1, 1, 0, 1, 0, 1, 1, 2, 0, 0, 1, 0]),
 array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 2, 0, 1, 1, 2, 0, 3, 0, 1, 2,
        0, 2, 1, 1, 2, 0, 0, 2, 3, 2, 0, 3, 0, 3, 1, 0, 3, 1, 2, 0, 0, 0,
        1, 4, 1, 0, 2, 1, 1, 2, 1, 1, 0, 3, 0, 2, 2, 1, 0, 2, 0, 0, 3, 1,
        2, 4, 1, 1, 1, 1, 3, 0, 0, 1, 2, 1, 0, 1, 3, 0, 2, 1, 0, 2, 2, 1,
        1, 1, 0, 1, 0, 1, 1, 2, 0, 0, 1, 0]),
 False)