In [13]:
from util_for_test import make_unique_eqs, finder, check
import numpy as np
max_n_op = 4
upper = 1.5
lower = 0.5
len_x = 40
how_many_to_save = 500000
x = np.random.uniform(lower, upper, (max_n_op + 1, len_x))
calced_x, calced_eq, arr_columns = make_unique_eqs(x, max_n_op, how_many_to_save=how_many_to_save, is_print=True, log_interval=120)

2025-05-20 01:59:39,710 : numba=0.61.2, numpy=2.2.4
2025-05-20 01:59:39,710 : OPT=_OptLevel(3), THREADING_LAYER=default
2025-05-20 01:59:39,710 : USING_SVML=False, ENABLE_AVX=True, DISABLE_JIT=0
2025-05-20 01:59:39,711 : SIS
2025-05-20 01:59:39,711 : num_threads=8, how_many_to_save=500000, 
2025-05-20 01:59:39,711 : how_many_to_save_per_1_core=63814, 
2025-05-20 01:59:39,711 : max_n_op=4, model_score=debug_1d, 
2025-05-20 01:59:39,712 : x.shape=(5, 40), is_use_1=True
2025-05-20 01:59:39,712 : use_binary_op=[-1, -2, -3, -4], 
2025-05-20 01:59:39,712 : use_unary_op=[]
2025-05-20 01:59:39,712 : units=[0] , [0] , [0] , [0] , [0]
2025-05-20 01:59:39,713 : compiling
2025-05-20 01:59:39,722 : END, compile
2025-05-20 01:59:39,731 :   n_op=1
2025-05-20 01:59:39,736 :     binary_op n_op1:n_op2 = 0:0,  loop:144
2025-05-20 01:59:39,763 :       time : 0:00:00.023009
2025-05-20 01:59:39,763 :     END, time=0:00:00.032163
2025-05-20 01:59:39,763 :   n_op=2
2025-05-20 01:59:39,764 :     binary_op n_op

In [ ]:
from util_for_test import make_unique_eqs, finder, check
import numpy as np
max_n_op = 4
upper = 1.5
lower = 0.5
len_x = 40
how_many_to_save = 500000
x = np.random.uniform(lower, upper, (max_n_op + 1, len_x))
calced_x, calced_eq, arr_columns = make_unique_eqs(x, max_n_op, how_many_to_save=how_many_to_save, is_print=True, log_interval=120)

2025-04-10 10:09:37,036 : numba=0.61.0, numpy=2.1.3
2025-04-10 10:09:37,036 : OPT=_OptLevel(3), THREADING_LAYER=default
2025-04-10 10:09:37,036 : USING_SVML=False, ENABLE_AVX=True, DISABLE_JIT=0
2025-04-10 10:09:37,037 : SIS
2025-04-10 10:09:37,037 : num_threads=8, how_many_to_save=500000, 
2025-04-10 10:09:37,037 : how_many_to_save_per_1_core=63814, 
2025-04-10 10:09:37,037 : max_n_op=4, model_score=debug_1d, 
2025-04-10 10:09:37,037 : x.shape=(5, 40), is_use_1=True
2025-04-10 10:09:37,038 : use_binary_op=[-1, -2, -3, -4], 
2025-04-10 10:09:37,038 : use_unary_op=[]
2025-04-10 10:09:37,038 : units=[0] , [0] , [0] , [0] , [0]
2025-04-10 10:09:37,038 : compiling


In [14]:
calced_eq.shape
## how_many_to_save -> 1 : 11, 2 : 236, 3 : 8147, 4 : 414872, 5 : 27963924

(414872, 9)

In [15]:
target_eq = np.array([1,2,3,-4,4,-3,1,-2,-4])
finder(target_eq, x=x, calced_x=calced_x, calced_eq=calced_eq)

finding : 
same :  [ 1  2  4 -3  3 -4  1 -2 -4]
done : make random_x


In [16]:
n_random = 1000000
find = ["not_calced", "many_calc"]# ["not_calced"]
check(n_random, x, calced_x, calced_eq, find, log_interval=5)

2025-05-20 01:59:58,237 :   24006/1000000  (498.2 MB)  0:00:05.005077 : 0:03:23.487675
2025-05-20 02:00:03,242 :   46809/1000000  (498.2 MB)  0:00:10.010073 : 0:03:23.839251
2025-05-20 02:00:08,247 :   69557/1000000  (498.2 MB)  0:00:15.015502 : 0:03:20.857839
2025-05-20 02:00:13,253 :   92704/1000000  (498.2 MB)  0:00:20.020912 : 0:03:15.945087
2025-05-20 02:00:18,258 :  116559/1000000  (498.2 MB)  0:00:25.026418 : 0:03:09.683883
2025-05-20 02:00:23,264 :  140488/1000000  (498.2 MB)  0:00:30.031847 : 0:03:03.736211
2025-05-20 02:00:28,269 :  164498/1000000  (498.2 MB)  0:00:35.037281 : 0:02:57.957898
2025-05-20 02:00:33,275 :  188283/1000000  (498.2 MB)  0:00:40.042722 : 0:02:52.630339
2025-05-20 02:00:38,280 :  211378/1000000  (498.2 MB)  0:00:45.048151 : 0:02:48.068403
2025-05-20 02:00:43,286 :  235442/1000000  (498.2 MB)  0:00:50.053619 : 0:02:42.540646
2025-05-20 02:00:48,291 :  259217/1000000  (498.2 MB)  0:00:55.059045 : 0:02:37.346179
2025-05-20 02:00:53,297 :  283167/1000000  

True

In [ ]:
many calc :  2 [ 5  3  0 -2  5  3 -2 -4 -3]
[ 0  5 -2  5  3 -4  0 -2 -4]
[ 0  3 -2  3  5 -4  0 -2 -4]

In [8]:
from util_for_test import finder
import numpy as np
target_eq = np.array([1, 2, -1, 3, -2, 4, 2, -1, -4])
finder(target_eq)

doing : make calced_x
done : make calced_x
finding : 
same :  [ 3  4 -1  1 -2  2  4 -1 -4]
done : make random_x


In [ ]:
[ 1  2  2 -3  1 -4  1 -2 -4]

In [ ]:
not calced :  [ 2  2  4  1  5 -4 -3 -2 -4] 0.09279815643807351
not calced :  [ 5  5  3  4  2 -4 -3 -1 -4] 1.622520828752577
not calced :  [ 4  5  1 -3  2 -4  4 -2 -4] 0.05453123325323784
not calced :  [ 5  5  1  4  2 -4 -3 -2 -4] 0.157141080172706
not calced :  [ 5  5  4  2  1 -4 -3 -2 -4] 0.05453123325323879
not calced :  [ 5  5  1  5 -4  1 -3 -1 -4] 1.5912550351971864
not calced :  [ 3  2  1 -4  5 -3  3 -2 -4] 0.1057777231470847
not calced :  [ 3  4  4 -3  3 -4  3 -2 -4] 0.0704404922652119
not calced :  [ 4  4  3  1 -4  2 -3 -1 -4] 0.8468567934189181

In [ ]:
from numba import njit, prange
import numpy as np

@njit(parallel=True, error_model="numpy")
def check_multi_or(arr_len, num_threads=8):
    save = np.zeros(arr_len, dtype="bool")
    a = np.zeros((num_threads, arr_len), dtype="bool")
    for thread_id in prange(num_threads):
        indexes = np.random.permutation(np.arange(arr_len))[:arr_len//num_threads]
        for i in indexes:
            a[thread_id, i] = True
            save[i] = True
    b = np.zeros(arr_len, dtype="bool")
    for thread_id in range(num_threads):
        b|=a[thread_id]
    return np.all(save == b)
check_multi_or(1000000, num_threads=18)

In [ ]:
from numba import njit, prange
import numpy as np

@njit(parallel=True, error_model="numpy")
def check_multi_plus(arr_len, num_threads=8):
    save = np.zeros(arr_len, dtype="int64")
    a = np.zeros((num_threads, arr_len), dtype="int64")
    for thread_id in prange(num_threads):
        indexes = np.random.permutation(np.arange(arr_len))[:arr_len//num_threads + 1]
        for i in indexes:
            a[thread_id, i] += 1
            save[i] += 1
    b = np.zeros(arr_len, dtype="int64")
    for thread_id in range(num_threads):
        b+=a[thread_id]
    #return np.all(save == b)
    return save, b, np.all(save == b)
check_multi_plus(100, num_threads=18)